### ISSUE TITLE
ADB Workshop Lab 4 - Needs step to provide user permission to load data

### ISSUE THREAD

**Issue by oscrub** [oracle/learning-library#1150]
Hi, I found that in [Lab 4: Load Data into ADB](https://oracle.github.io/learning-library/data-management-library/autonomous-database/shared/adb-journey-workshop/index.html?lab=lab-4-load-data-into-adb) in the Journey to Autonomous Database Workshop series, by default the user created is not allowed to read and load the data from the bucket to the ADW database.

The needed steps are to create a group, add the user to the group, and create a policy with the following statements:

```
Allow group <GroupName> to read buckets in compartment <CmptName>
Allow group <GroupName> to read objects in compartment <CmptName>
```

You can also apply the policy to the tenancy rather than the compartment, depending on the setup. 

Also, another available workaround without having to create a group and assign policies is to create the bucket as a public bucket rather than a private one.

**Comment by kaymalcolm** [comment]
Hi @oscrub, please provide the link to the lab.  Thanks!

**Comment by oscrub** [comment]
Hi @kaymalcolm, sure, here's the link:

https://oracle.github.io/learning-library/data-management-library/autonomous-database/shared/adb-journey-workshop/index.html?lab=lab-4-load-data-into-adb

**Comment by kaymalcolm** [comment]
@nilaypanchal This one is for you.

**Comment by aminadatia** [comment]
The link to the data gives Error 404

**Comment by oscrub** [comment]
I think this is the new URL for the lab: 

https://oracle.github.io/learning-library/data-management-library/autonomous-database/shared/workshops/freetier-overview/?lab=lab-4-load-data-into-adb

**Comment by aminadatia** [comment]
Thanks!

There are still links that do not work. I did get one spreadsheet -- Channels -- but the link to the script to create the table is 404 Error


Regards

Amin Adatia
613-864-8378

________________________________

**Comment by kaymalcolm** [comment]
Hi @aminadatia, @greenrick is the owner of this lab.  I will let him know and get this fixed.

**Comment by tmcginn** [comment]
@greenrick - did you resolve this issue?

**Comment by aminadatia** [comment]
Hi

No.


Regards


Amin Adatia
613-864-8378

________________________________

**Comment by greenrick** [comment]
@oscrub and @aminadatia Hello, thanks for inquiring and sorry for the links not working. oscrub, in your initial 30th of March inquiry, you provided a link to a "Journey" workshop that might be an older, outdated workshop. On the 11th of May, you provided a link to the latest updated version of the lab. At what numbered steps in this latest version of the lab are you experiencing the user access problem? 
Step 7 mentions "To load data from the Oracle Cloud Infrastructure(OCI) Object Storage you will need an OCI user with the **appropriate privileges** to read data (or upload) data to the Object Store." Our instructions only say to **select** a user; @nilaypanchal do we need instead to add steps to define an OCI user, create a group, add user to the group, and create a policy to grant the group read access to the compartment or tenancy - **or** as oscrub suggests, simply create the bucket as a public bucket rather than a private one?

**Comment by nilaypanchal** [comment]
Thanks for pointing me to this Rick, I didn't see these before.
Yes, as mentioned here we assume the user coming in has a Cloud account with the necessary privileges. @greenrick it doesn't make sense to list how to create a user and policy etc. as part of this lab because that is an OCI tutorial and the user may or may not have the necessary access to be able to do that - They would have to contact their Cloud Admin.

We can put in a note to say something similar as the older OBE Tutorials: 

If you will be uploading data files to an object store in Oracle Cloud Infrastructure Object Storage, your cloud administrator or lab instructor must provide your cloud user with read/write privileges to the object store location where the data is to be stored.

And point to the Object Store Docs
https://docs.cloud.oracle.com/en-us/iaas/Content/StorageGateway/Tasks/interactingwithobjectstorage.htm#createIAM

It is not a best practice to use a public bucket in production because it is open to the public internet and so we steer away from doing so in tutorials too. Create a public bucket also needs certain user privileges.

**Comment by aminadatia** [comment]
Hi!

I was using my account in DBW Cloud and also my database on my desktop. and in neither could I get ahead. So obviously I am missing something. Just would like to know what it is.


Regards


Amin Adatia
613-864-8378

________________________________

**Comment by tmcginn** [comment]
Hi Amin, we really need more information - can you provide the URL of the workshop, the step and substep number and what symptom or specific error you encountered?
Thanks, Tom

**Comment by aminadatia** [comment]
Hi!

I am going to reinstall my Oracle 19.3 on the desktop. Maybe something really strange is going on because on a new install on my laptop the Data Miner errors about orageneric11.dll do not appear but on the Desktop they do.

I will try again afterwards and let you know.


Regards


Amin Adatia
613-864-8378

________________________________

**Comment by tmcginn** [comment]
Hi Amin, I think that you are working on a different workshop or lab. This workshop does not use a desktop/on-premises database. If you continue to have an issue, please open a new issue with the workshop name, step and substep information please.
Tom
