### ISSUE TITLE
Access Issue Step1 Option1 of HOL Lab4 for Microservices/Serverless (Giggi's Pizza)

### ISSUE THREAD

**Issue by BXK20** [oracle/learning-library#1358]
When accessing the OVA image in step 1 Option 1 of the HOL Lab 4 at  https://oracle.github.io/learning-library/developer-library/microservices-serverless-workshop/?lab=lab-4-install-front-end-client

I am getting error : {"code":"NotAuthenticated","message":"The required information to complete authentication was not provided."}

The link which it is trying to access when clicked is : https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/hZnw2wJSeVpigjnOHBwSO9-GcZrdNyjqgWi1FObBvHg/n/wedoinfra/b/DevCS_Clone_WedoDevops/o/HOL5967-OOW2019.ova

**Comment by oraclespainpresales** [comment]
Hi the new preauthenticated key is https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/smpE_ekRW19rd4H31B4fPspIqXxRm-iSuaQ9kOc8_K8/n/wedoinfra/b/DevCS_Clone_WedoDevops/o/HOL5967-OOW2019%20OVAHOL5967-OOW2019.ova

Sorry about that

**Comment by anooshapilli** [comment]
Hi, the pre-authenticated key was expired. You can use this new one - 

https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/smpE_ekRW19rd4H31B4fPspIqXxRm-iSuaQ9kOc8_K8/n/wedoinfra/b/DevCS_Clone_WedoDevops/o/HOL5967-OOW2019%20OVAHOL5967-OOW2019.ova

The other option is to use the cloud shell because the ova image is used to execute oci, kubectl, and fn commands.

**Comment by troyanthony06** [comment]
Tom's fix merged. This should correct the issue once deployed.
