### ISSUE TITLE
Build - fails on ms_payment_docker_Create in Gigi's Pizza work shop microservice build

### ISSUE THREAD

**Issue by BXK20** [oracle/learning-library#1368]
Here is the message in build log:
[2020-05-25 15:04:33] denied: User UserId(ocid1.user.oc1..aaaaaaaar6jyoqubdoots7hztl27bv57xlykoyswbqnlhz6z3cwyaeenspfa) cannot UploadDockerLayer on resource wedoinfra/wedodevops/mspayment
[2020-05-25 15:04:33] Error: Command exited with status 1

[ms_payment_docker_create-66-log.txt](https://github.com/oracle/learning-library/files/4678740/ms_payment_docker_create-66-log.txt)

**Comment by anooshapilli** [comment]
According to the log docker build -t iad.ocir.io/wedoinfra/wedodevops/mspayment ./target

but the correct command should be docker build -t iad.ocir.io/<your_object_storage_namespace>/wedodevops/mspayment ./target

Same for all commands in all jobs. In the HOL appears "wedoinfra" because is the object_storage_namespace of the tenancy used to create the HOL.

**Comment by tmcginn** [comment]
@anooshapilli - can I close this issue?

**Comment by anooshapilli** [comment]
@tmcginn - yes, can close this issue.
