### ISSUE TITLE
tenancy name/region

### ISSUE THREAD

**Issue by davidhay** [oracle/learning-library#364]
There is a LOT going on in the first LAB100 including account setup etc. To build confidence - students want things to work - especially with the first lab. It's not a great feeling to find problems after following ( and double checking)  the instructions to EVENTUALLY see this comments pretty much AT THE BOTTOM: "NOTE: If you receive an error message that says Tenant with name XYZ not found, don't worry. Your cloud account may be in a different region than we specified in the environment variable above. We will correct that in the next lab, once we log in to the OCI console." :-( 
I don't recall the instructor mentioning this potential gotcha either.

**Comment by derekoneil** [comment]
David,

Thanks for your comment. While the flow of the labs has been informed by past technical limitations and considerations, the technology has evolved and it is no longer necessary to do the Wercker tasks first. I will restructure the labs so that the required information is obtained in a more natural way in advance of when it is required. This will mean that the lab 200 actions of going into the OCI console and creating a K8s cluster and other resources will become the first lab, and creating the build and deploy pipelines will come in the second lab. This way we will have seen and touched all the prerequisite infrastructure before trying to build automation on it.

Thanks for your perspective.

-Derek
